theme = "base16_transparent"

[editor]
scrolloff = 15
auto-format = true
true-color = true
gutters = ["diagnostics", "spacer", "diff"]

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'`' = '`'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[keys.normal]
# Personal preference
o = ["open_below", "normal_mode"]
O = ["open_above", "normal_mode"]

# Muscle memory
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
"C-b" = []                                          # Unbinds Ctrl-b in normal mode
"C-n" = ["move_line_down", "move_visual_line_down"]
"C-p" = ["move_line_up", "move_visual_line_up"]


[keys.insert.j]
"j" = ["normal_mode"]

[keys.insert]
"C-y" = ["completion"]

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true
