theme = "base16_transparent"
# theme = "carbonfox"
[editor]
scrolloff = 15
auto-format = true
continue-comments = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.auto-save]
focus-lost = true

[editor.lsp]
enable = true
display-messages = false
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = false
snippets = true
goto-reference-include-declaration = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.smart-tab]
enable = false

[keys.normal]
# Personal preference
# o = ["open_below", "normal_mode"]
# O = ["open_above", "normal_mode"]

G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
"C-b" = []                                   # Unbinds Ctrl-b in normal mode
"C-n" = ["move_line_down"]
"C-p" = ["move_line_up"]

[keys.insert]
"C-y" = ["completion"]
"C-n" = ["move_line_down"]
"C-p" = ["move_line_up"]


[keys.insert.j]
"j" = ["normal_mode"]

# [keys.normal.space]
# "t" = [
#   "yank_to_clipboard",
#   ":sh tmux paste-buffer -t right; tmux send-keys -t right Enter",
# ]

[keys.normal.space]
"t" = ["yank_to_clipboard", ":sh send-to-zellij"]

[keys.normal.space.w]
"w" = [":write"]

[keys.normal.space.q]
"q" = [":quit-all"]
