theme = "base16_transparent"

[editor]
scrolloff = 15
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.auto-save]
focus-lost = true

[editor.gutters]
layout = ["diff", "diagnostics", "spacer"]

[editor.lsp]
enable = true
display-messages = false
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = false
snippets = true
goto-reference-include-declaration = true

[editor.smart-tab]
enable = false

[keys.normal]
# Personal preference
o = ["open_below", "normal_mode"]
O = ["open_above", "normal_mode"]

# Muscle memory
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
"C-b" = []                                          # Unbinds Ctrl-b in normal mode
"C-y" = ["completion"]

[keys.insert.j]
"j" = ["normal_mode"]

[keys.normal.space]
"t" = [
  "yank_to_clipboard",
  ":sh tmux paste-buffer -t right; tmux send-keys -t right Enter",
]
